### ISSUE TITLE
Compiler: derived map

### ISSUE THREAD

**Issue by Locke** [CoreASM/coreasm.core#13]
I noticed a case where the compiler semantics doesn't match the interpreter semantics:

```
CoreASM DerivedTest

use Standard

init Start

derived mySqrt(x) = x * x

derived myMap = {
        0 -> "Null",
        1 -> "One",
        2 -> "Two",
        3 -> "Three"
}

rule Start = {
        print "mySqrt(3): " + mySqrt(3)
        //print "myMap()(3): " + myMap()(3) // this line does not compile
        let x = myMap() in
                print "x(3): " + x(3) // prints undef when compiled
}
```

`mySqrt` is working fine (I just put it there to confirm that the Signature Plugin is working), but the map is inaccessible. It looks like `x` is stored on the localstack but read from the Storage. `myMap()(3)` does not compile with the error `plugin KernelExtensionsPlugin is not compilable but mandatory`.

**Comment by Spellmaker** [comment]
The reason for this problem is, that the Kernel Extensions Plugin is not implemented, which the
compiler remarks with "plugin KernelExtensionsPlugin is not compilable but mandatory".
I started implementing the plugin and will push it with the next commit.
