### ISSUE TITLE
find defined locations of function

### ISSUE THREAD

**Issue by Locke** [CoreASM/coreasm.core#15]
Is it possible to find out the locations a function is defined at?

For example with this definitions:
```
function A : Agents -> NUMBER
function B : STRING -> NUMBER
```

I could do `forall a in Agents with A(a) != undef do { ... }`, however, how could I achieve this for `B`?

**Comment by mdausend** [comment]
As STRING is not an enumerable universe, it is not possible to get the locations similar to your example for function A, where Agents is an enumerable universe.

You can use the debugger of the eclipse plugin to find out the locations and there values of a function.
![debugger](https://cloud.githubusercontent.com/assets/2181912/6848584/6132b16e-d3ce-11e4-824b-28ced93b04e7.png)

**Comment by Locke** [comment]
Thanks for the fast response, I hoped for an undocumented feature. Looks like I have to keep track of the locations in a set
