### ISSUE TITLE
filter lists depending on "environment variables"

### ISSUE THREAD

**Issue by Locke** [CoreASM/coreasm.core#17]
Hi,

I need to filter lists depending on "environment variables".

I use this approach which works fine until commit 039d116:

```
derived environmentFilter(x) = (x > y)

rule testEnvironmentFilter = {
	let y = 7 in {
		print "testEnvironmentFilter: " + filter(myList, @environmentFilter)
	}
}

init Start

rule Start = {
	seqblock
		myList := [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
		testEnvironmentFilter()
	endseqblock
	program(self) := undef
}
```

Can you suggest me an alternative approach? With the hiding of environment variables I don't see any way to pass `y` to the function that is used by the filter.

**Comment by mstegmaier** [comment]
Hi Locke,

sorry for late reply. I didn't see this issue until now.
You could do
local y := 7 in print "testEnvironmentFilter: " + filter(myList, @environmentFilter)
instead.
