### ISSUE TITLE
CoreASMError: Cannot apply updates when state stack is empty

### ISSUE THREAD

**Issue by Locke** [CoreASM/coreasm.core#20]
Hi,

after a minor refactoring of my specification the Engine crashs now with the CoreASMError: `Cannot apply updates when state stack is empty` from HashStorage.java:475 (using the current master). It also crashes in 3966cc7c4b1944c9c6b2c34fbddadb99b1dbd5c5, but I can't test older revisions as I use `foreach`.

When I revert to the state before the refactoring it works fine. However I couldn't narrow down which of my edits is responsible for the crash, I'm still working on that. But even if I did something wrong in my specification the Engine should crash with a nicer message, so I assume a bug in the Engine.

Here is the stacktrace (some line numbers could be wrong as I added some logging statements):

```
org.coreasm.engine.CoreASMError: Cannot apply updates when state stack is empty.
	at org.coreasm.engine.Engine.error(Engine.java:632)
	at org.coreasm.engine.Engine.error(Engine.java:618)
	at org.coreasm.engine.absstorage.HashStorage.apply(HashStorage.java:486)
	at org.coreasm.engine.plugins.turboasm.TurboASMPlugin.interpret(TurboASMPlugin.java:435)
	at org.coreasm.engine.interpreter.InterpreterImp.executeTree(InterpreterImp.java:144)
	at org.coreasm.engine.scheduler.ConcurrentProgramEvaluator.evaluate(ConcurrentProgramEvaluator.java:176)
	at org.coreasm.engine.scheduler.ConcurrentProgramEvaluator.run(ConcurrentProgramEvaluator.java:115)
	at EDU.oswego.cs.dl.util.concurrent.FJTaskRunner.scanWhileIdling(Unknown Source)
	at EDU.oswego.cs.dl.util.concurrent.FJTaskRunner.run(Unknown Source)
```

I cannot give you the full specification, and also couldn't write a small "crashing" example / testcase.

Basicly the specification has a main loop like this:

```
function agentTasks : Agents -> LIST
function skipNextTasks : Agents -> BOOLEAN
function tasks : -> LIST

rule MainLoop = {
	local tasks in seqblock
		tasks := agentTasks(self)

		while (|tasks| > 0) do
		let currentTask     = head(tasks) in
		let currentTaskID   = nth(currentTask, 1) in 
		let currentTaskType = nth(currentTask, 2) in seqblock

			ExecuteTask(currentTaskID)

			if (skipNextTasks(self) = true) then {
				debuginfo MainLoop "next tasks should not be executed"
				tasks := []
			}
			else if (currentTaskType = "special") then {
				debuginfo MainLoop "only special next tasks should be executed"
				tasks := filterSpecial(tasks)
			}
			else {
				debuginfo MainLoop "continue with next tasks (unfiltered)"
				tasks := tail(tasks)
			}

			debuginfo MainLoop "next tasks: " + tasks
		endseqblock

		debuginfo MainLoop "main loop ended"
	endseqblock
}

rule Execute = seqblock
	Debug_PrintState

	MainLoop
endseqblock
```

Within ExecuteTask lies the complete logic like modifying `agentTasks` for the next iteration, and having a lot of `let`, `foreach`, `while` and even again `local tasks` in sub-rules / derived functions.

I get the debug info "next tasks: []", but then the crash occurs and "main loop ended" will not be printed.

From what I've read in `HashStorage.java` incremental updates (like seq, while, foreach) work with stacked states, so I've logged all calls to `pushState` and `popState`:

```
locke@VirtualBox:/tmp$ cat log | grep pushState | grep TurboASMPlugin | wc -l
237
locke@VirtualBox:/tmp$ cat log | grep popState | grep TurboASMPlug | wc -l
227


locke@VirtualBox:/tmp$ cat log | grep pushState | grep LetRulePlugin | wc -l
189
locke@VirtualBox:/tmp$ cat log | grep popState | grep LetRulePlugin | wc -l
193


locke@VirtualBox:/tmp$ cat log | grep pushState | grep ForeachRulePlugin | wc -l
18
locke@VirtualBox:/tmp$ cat log | grep popState | grep ForeachRulePlugin | wc -l
34
```

I expected these numbers to be identical or about off-by-one and hoped to find the error by myself, however I'm suprised that there are a lot more `popState` than `pushState`. So without more knowledge about the internals I'm stuck.

As I can't give a full example: can you give me some ideas how I could continue identifying the problem, or do you even see from the example and description what went wrong?

**Comment by mstegmaier** [comment]
Hi Locke,

I'll look into it but we've never experienced this issue so far... so without a full example to reproduce it it will be hard to identify.
Please let us know if you find out more.

**Comment by Locke** [comment]
Hi mstegmaier,

just to keep you posted: I spend some more time looking into this but couldn't find the cause of it. It also happens with the current master. I'll take some more time for this next week.

**Comment by mstegmaier** [comment]
Hi Locke,

I've just reviewed everything related to `popState` and `pushState` and pushed some improvements to the relevant parts of code.
Could you please check if my changes have solved the issue?

**Comment by Locke** [comment]
Well, it's not crashing anymore - just ending up in a deadlock :(

**Comment by Locke** [comment]
I just re-read (some parts of) chapter 2.4 of the ASM book and realized I may did a huge mistake in my specification. I'll close this issue for now until I've revised everything.

I think I will be able to bring up an example to demonstrate what went wrong and how to detect this without running in an endless loop / crashing.

**Comment by Locke** [comment]
The "huge mistake" wasn't that big after all, I simply forgot over the time on one place that ASMs are call-by-name and created an endless loop with some references.

Now I'm hit again by the `Cannot apply updates when state stack is empty` and have some more weird observations, however again no testcase that I could share. It really could be a mistake on my side again, but I believe in that case there should be a better hint from the Engine, so I'm re-opening this issue.

First observation (sketch):

```
rule A = {
  let x = 1 in {
    print "A_x = " + x
    B()
  }
}

rule B = {
  print "B1_x: " + x
  let x = 2 in {
    print "B2_x: " + x
  }
}
```

Under some conditions I get reproducible the warning `x collides with an environment variable.` on the `let x = 2` statement. However in B1_x it is printed as `undef`. (With `option Signature.NoUndefinedId strict` enabled it crashes on the print). Under most conditions I don't get that warning.

Second observation (sketch):

```
function x : LIST * NUMBER * NUMBER -> NUMBER

rule A = {
  seqblock
  x(["a"], 0, 0) := undef
  // debuginfo A "x: " + x(["a"], 0, 0)
  B()
  // debuginfo A "x: " + x(["a"], 0, 0)
  let y = x(["a"], 0, 0) in {
    if (y = undef) then {
      print "undef!"
    }
    else {
      print "not undef"
    }
  }
  endseqblock
}
```

B may set x or not. Under some conditions y is undef even though it should not be. When I enable the debuginfos the correct value is set and y is not undef (as expected).

**Comment by mstegmaier** [comment]
I just tried both of your examples multiple times and they always behaved the same way as expected. Could you please provide examples that actually let me reproduce the described behavior? It might already be helpful if you specified what you mean by "under some conditions".

**Comment by Locke** [comment]
> I just tried both of your examples multiple times and they always behaved the same way as expected.

They are not full examples as I tried to indicate with **sketch**, they represent the rough structure.

I cannot give you the complete specification, but I'll try to create a example.

Regarding `x collides with an environment variable` I noticed tonight that the warning only happens when the rule has arguments, and it happens on the usage of `x` and not as I stated earlier in the `let x = 2` statement. Here is a complete example:

```
CoreASM Test

use Standard

init A

rule A = {
  let x = 1 in {
    print "A_x = " + x
    B(1)
    C()
  }

  program(self) := undef
}

rule B(y) = {
  print "B1_x: " + x // WARNING (Kernel): "x" collides with an environment variable. // WARNING (NumberPlugin): The right operand of the '+' operator was undef.
  let x = 2 in {
    print "B2_x: " + x // WARNING (Kernel): "x" collides with an environment variable.
  }
}

rule C = {
  print "C1_x: " + x // WARNING (NumberPlugin): The right operand of the '+' operator was undef.
  let x = 2 in {
    print "C2_x: " + x
  }
}
```

**Comment by Locke** [comment]
I reduced it as far as I could, this is a full example for "Cannot apply updates when state stack is empty". Due to the reduction it doesn't do anything useful but you should be able to investigate the problem with it:

```
CoreASM TestEmptyStack

use Standard
use ForeachRule

init Test

rule Test = {
    foreach a in [1, 2] do {
        forall b in foo do {
            skip
        }
    }

    program(self) := undef
}

function x : -> SET

derived foo = return x in {
    seqblock
        x := {}
        foreach y in {3} with (y > 10) do
            skip
    endseqblock
}
```

**Comment by mstegmaier** [comment]
Hi Locke,

thanks for the example. It helped a lot to quickly track down the issue and now it's fixed. :)

**Comment by Locke** [comment]
Hello,

again, thanks for the fast fix. With the stacked plugin names it should be much easier to discover similar problems in the future :)
