### ISSUE TITLE
guarded foreach stuck in endless loop

### ISSUE THREAD

**Issue by Locke** [CoreASM/coreasm.core#21]
The deadlock I mentioned in #20 turned out to be a bug regarding `foreach`.

Somewhere between dc3753fd and 49dd3ab3 `foreach` gets stuck in an endless loop if there are no elements where the `with` condition holds.

```
foreach x in [1, 2, 3] with (x > 5) do {
    print "x: " + x
}

print "done"
```

If you use an more complex guard containing a debuginfo you can see that it is evaluated for all elements over and over again.

Note: using an empty list works as expected

**Comment by mstegmaier** [comment]
Thanks for analysing this issue. I've fixed it now.

**Comment by Locke** [comment]
Thanks for the fast fix, now it works like a charm, and also much faster thanks to the recent improvements with Thread.yield :+1: 

My problem in #20 turned out to be a minor one after all. Over the time I had forgotten that ASM Rules are call-by-name and had an instance where I had to "freeze" the arguments via `let` before passing them along.
