### ISSUE TITLE
TestAllCasm: options no longer applied

### ISSUE THREAD

**Issue by Locke** [CoreASM/coreasm.core#23]
Since [Improved the integration of options](https://github.com/CoreASM/coreasm.core/commit/111d90ca6cce00c00625037bd43ea2cf0c07f9d3) options are no longer loaded by TestAllCasm. For example test/plugins/debuginfo/Debug1.java runs with the previous commit, but not with the new option handling. In the DebugInfoPlugin `activeChannels` remains empty.

**Comment by mstegmaier** [comment]
Should be fixed now.

**Comment by Locke** [comment]
Tanks for the quick fix
