### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by Locke** [CoreASM/coreasm.core#24]
Hi,

I want to create a new release of my own project. Can you publish a new version of CoreASM within the next few weeks? I don't want to have a SNAPSHOT dependency but need to include the fixes for #20 and #21.

By the way, the recent changes regarding performance (db0527e5...e4efdf74, for reference) don't improve the performance much for my test files (at most 5%), but it seems you were concerned more about code quality and memory consumption which I didn't measure.

**Comment by mstegmaier** [comment]
Changes regarding performance? What makes them regard performance?

What do you mean by publish a new version? Do you mean publish to maven central repository? We could do that soon I guess.

What is your own project? Is there anything to take a look at?

**Comment by Locke** [comment]
> Changes regarding performance? What makes them regard performance?

I didn't look too much into the source code changes. I had the impression because avoiding manual copies of collections tend to be more performant in general (e.g. `Iterate over the elements instead of creating a copy and removing each element one by one` and the usage of Iterators instead of Lists).

> What do you mean by publish a new version? Do you mean publish to maven central repository?

Yes, what else could I have meant?

> We could do that soon I guess.

Thanks.

> What is your own project? Is there anything to take a look at?

Unfortunately the project has to stay closed source for the moment, but I hope to publish it someday. I will inform you when there is something published.

**Comment by mstegmaier** [comment]
> Yes, what else could I have meant?

CoreASM is also published in the Eclipse Marketplace and eclipse plugins can also have dependencies to eachother.

> Unfortunately the project has to stay closed source for the moment, but I hope to publish it someday. I will inform you when there is something published.

Thank you, we are looking forward to seeing it.

**Comment by mstegmaier** [comment]
Hi Locke,

we're currently in the end of semester stress and didn't find any time for the release yet. So unfortunately it will take even longer until we can publish the new release.

Sorry for any inconvenience this might cause.

**Comment by mdausend** [comment]
Catch up on closing this issue ;-)
