### ISSUE TITLE
Publish CoreASM artifacts in maven repository

### ISSUE THREAD

**Issue by ladenberger** [CoreASM/coreasm.core#8]
Hello,

do you consider to publish the artifacts in a maven repository? This would be great for other maven projects that want to use the CoreASM libraries.

Best regards,
Lukas

**Comment by mdausend** [comment]
I deployed the current snapshots to the ossrh maven repository. It can be found at https://oss.sonatype.org/#nexus-search;quick~coreasm
Please be patient for the first release deploy.
